/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdadb',
        'on-background': '#dce1fb',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#ffb2b7',
        'primary-container': '#a078ff',
        'on-secondary-fixed-variant': '#004e5a',
        surface: '#0c1324',
        'surface-variant': '#2e3447',
        'error-container': '#93000a',
        primary: '#d0bcff',
        'primary-fixed': '#e9ddff',
        'on-tertiary-fixed-variant': '#92002a',
        'on-secondary': '#00363e',
        'inverse-on-surface': '#2a3043',
        'surface-bright': '#33394c',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-container': '#5b0017',
        'on-primary': '#3c0091',
        'outline-variant': '#494454',
        'on-error-container': '#ffdad6',
        'secondary-container': '#00cbe6',
        'surface-container-low': '#151b2d',
        background: '#0c1324',
        'on-tertiary': '#67001b',
        'primary-fixed-dim': '#d0bcff',
        'secondary-fixed-dim': '#2fd9f4',
        'on-secondary-fixed': '#001f25',
        secondary: '#5de6ff',
        'surface-container': '#191f31',
        tertiary: '#ffb2b7',
        'secondary-fixed': '#a2eeff',
        outline: '#958ea0',
        'inverse-surface': '#dce1fb',
        'on-primary-fixed': '#23005c',
        'on-surface': '#dce1fb',
        'on-primary-container': '#340080',
        'surface-container-highest': '#2e3447',
        'on-primary-fixed-variant': '#5516be',
        'surface-tint': '#d0bcff',
        'on-secondary-container': '#00515d',
        'surface-container-high': '#23293c',
        'surface-dim': '#0c1324',
        'on-error': '#690005',
        'tertiary-container': '#ff516a',
        'inverse-primary': '#6d3bd7',
        'on-surface-variant': '#cbc3d7',
        'surface-container-lowest': '#070d1f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'panel-padding': '12px',
        gutter: '16px',
        'margin-mobile': '12px',
        'margin-desktop': '24px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': [
          '14px',
          {
            lineHeight: '20px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '0em',
            fontWeight: '600',
          },
        ],
        'headline-md': [
          '24px',
          {
            lineHeight: '32px',
            letterSpacing: '0em',
            fontWeight: '600',
          },
        ],
        'body-md': [
          '16px',
          {
            lineHeight: '24px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'label-mono': [
          '13px',
          {
            lineHeight: '16px',
            letterSpacing: '0.02em',
            fontWeight: '500',
          },
        ],
        'code-sm': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
      },
    },
  },
  plugins: [],
};
